name: haskoin-store
version: 0.3.0
synopsis: Storage and index for Bitcoin and Bitcoin Cash
description: Store blocks, transactions, and balances for Bitcoin or Bitcoin Cash, and make that information via REST API.
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin.git
homepage: http://github.com/haskoin/haskoin#readme
bug-reports: http://github.com/haskoin/haskoin/issues
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - base >=4.7 && <5
  - data-default
  - haskoin-core
  - haskoin-node
  - monad-logger
  - nqe
  - rocksdb-haskell
  - unliftio
library:
  source-dirs: src
  exposed-modules:
    - Haskoin.Store
  dependencies:
    - aeson
    - bytestring
    - cereal
    - conduit
    - containers
    - hashable
    - mtl
    - network
    - random
    - rocksdb-query
    - string-conversions
    - text
    - time
    - transformers
    - unordered-containers
executables:
  haskoin-store:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskoin-store
      - aeson
      - bytestring
      - conduit
      - directory
      - filepath
      - http-types
      - optparse-applicative
      - scotty
      - string-conversions
      - text
tests:
  haskoin-store-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hspec
      - haskoin-store
      - mtl
