name: haskoin-store
version: 0.23.18
synopsis: Storage and index for Bitcoin and Bitcoin Cash
description: >
  Store and index Bitcoin or Bitcoin Cash blocks, transactions,
  balances and unspent outputs.

  All data is available via REST API in JSON or binary format.

  Uses in-process RocksDB database to store data.

  Supports Redis cache that can be shared by multiple nodes for
  faster access to extended public key balances, transactions
  and unspent outputs.
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: jprupp@protonmail.ch
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin-store.git
homepage: http://github.com/haskoin/haskoin-store#readme
bug-reports: http://github.com/haskoin/haskoin-store/issues
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  aeson: ">= 1.4.7.1"
  base: ">=4.9 && <5"
  bytestring: ">= 0.10.10.0"
  cereal: ">= 0.5.8.1"
  conduit: ">= 1.3.2"
  containers: ">= 0.6.2.1"
  data-default: ">= 0.7.1.1"
  deepseq: ">= 1.4.4.0"
  hashable: ">= 1.3.0.0"
  monad-logger: ">= 0.3.32"
  mtl: ">= 2.2.2"
  haskoin-core: ">= 0.12.0"
  nqe: ">= 0.6.1"
  random: ">= 1.1"
  string-conversions: ">= 0.4.0.1"
  text: ">= 1.2.4.0"
  time: ">= 1.9.3"
  transformers: ">= 0.5.6.2"
  unliftio: ">= 0.2.12.1"
  unordered-containers: ">= 0.2.10.0"
library:
  source-dirs: src
  generated-exposed-modules:
    - Paths_haskoin_store
  exposed-modules:
    - Haskoin.Store
  dependencies: &lib-deps
    hedis: ">= 0.12.13"
    http-types: ">= 0.12.3"
    haskoin-node: ">= 0.11.0"
    network: ">= 3.1.1.1"
    rocksdb-haskell: ">= 1.0.1"
    rocksdb-query: ">= 0.3.1"
    scotty: ">= 0.11.5"
    wai: ">= 3.2.2.1"
    warp: ">= 3.3.10"
executables:
  haskoin-store:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskoin-store
      - filepath
      - optparse-applicative
tests:
  haskoin-store-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      <<: *lib-deps
      hspec: ">= 2.7.1"
      QuickCheck: ">= 2.13.2"
