resolver: lts-16.24
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - github: haskoin/haskoin-core
    commit: 323433e680b6793b4b5dc91d19fd79992cdf2d4c
  - haskoin-node-0.17.1
  - secp256k1-haskell-0.5.0
  - rocksdb-haskell-jprupp-2.1.3
  - rocksdb-query-0.4.2
