resolver: lts-17.12
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - git: https://github.com/haskoin/haskoin-core.git
    commit: 147152343cde3a86aa98af2272f52b955d89d971
  - git: https://github.com/haskoin/haskoin-node.git
    commit: 35ad6937bc0fceaa05385582ffd2b8f17f7d9b49
