resolver: lts-23.0
ghc-options:
  "$everything": -O2
nix:
  packages:
  - perl
  - rocksdb
  - secp256k1
  - zlib
  - pkg-config
  - cacert
packages:
  - store
  - data
extra-deps:
  - statsd-rupp-0.5.0.0@sha256:04049a06a6a92aaecd052d1caa36321bfc68c43bcc8e48e93b1f87218c182e0b,2017
