resolver: lts-12.9
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
extra-deps:
  - rocksdb-haskell-1.0.1
  - murmur3-1.0.3
  - secp256k1-haskell-0.1.2
  - nqe-0.5.0
  - github: haskoin/haskoin-core
    commit: 5cea2fe6b44d0b3fd99a1e78ec37d36361b61d79
  - github: xenog/rocksdb-query
    commit: ffba9ee46d9aba19b96eb16c685d99df1c66ce04
  - github: haskoin/haskoin-node
    commit: a5b5139369db6e41923dbabd7aefe5a7c02cc692
