resolver: lts-19.16
nix:
  packages:
  - perl
  - rocksdb
  - secp256k1
  - zlib
  - pkg-config
  - cacert
packages:
  - store
  - data
allow-newer: true
extra-deps:
  - git: https://github.com/tibbe/ekg-core.git
    commit: ddf7c1eb6d487b0e17ac1ce8428b6d9daea2f671
  - git: https://github.com/haskoin/haskoin-node.git
    commit: 00b5ebdc04f2a246dac7acf802fa2c3b46e9cfb4
  - git: https://github.com/tibbe/ekg-statsd.git
    commit: c6a9760266277cbd7641e9618f3b7cfbabc299d1
