resolver: nightly-2023-11-09
nix:
  packages:
  - perl
  - rocksdb
  - secp256k1
  - zlib
  - pkg-config
  - cacert
packages:
  - store
  - data
ghc-options:
  "$everything": -O2
extra-deps:
  - statsd-rupp-0.4.0.4@sha256:5b6c290488e2117ee9d19f3e836ae349f2756103b2bd7ac3c2102e0b1be156a9,2017
