resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
packages:
  - store
extra-deps:
  - github: haskoin/haskoin-core
    commit: d313ac58b2f22fa7570a5e1234244b7249a48382
  - github: haskoin/haskoin-node
    commit: 17ecd00e7336f154d6dd3e00f2eadbece8221aa5
  - github: haskoin/secp256k1-haskell
    commit: 239159122cc6f830957759a1d247ded7ffeba915
  - github: jprupp/nqe
    commit: acbed8c6f39055b33e9c24de3ce634cfc2d8de88
  - ./data
