resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
packages:
  - store
  - data
extra-deps:
  - github: haskoin/haskoin-core
    commit: c90b178dd478e7f268dce0c8de9a49708f8a5774
  - github: haskoin/haskoin-node
    commit: f6de51536d0638dab9021bc7e32e9259a847cc35
  - github: haskoin/secp256k1-haskell
    commit: 5430374aceca6726765fb80c3782b005482804ef
  - github: jprupp/nqe
    commit: acbed8c6f39055b33e9c24de3ce634cfc2d8de88
  - github: jprupp/rocksdb-haskell
    commit: 7bc824e8d07ed5a776735caae0b52fc1edf7286d
  - github: jprupp/rocksdb-query
    commit: b1a6f9a5e44f21d641f4b9343329e194ef6be6ba
