resolver: lts-18.28
nix:
  packages:
  - perl
  - rocksdb
  - secp256k1
  - zlib
  - pkg-config
  - cacert
packages:
- store
- data
extra-deps:
- git: https://github.com/haskoin/haskoin-core.git
  commit: 2a13ee8be20d7cd3646bb73dc5da4beeaf409ee2
- git: https://github.com/haskoin/haskoin-node.git
  commit: 6fd1388fa9160629aaebcec2c738aae5dcca9d88
- git: https://github.com/tibbe/ekg-core.git
  commit: ddf7c1eb6d487b0e17ac1ce8428b6d9daea2f671

