resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
packages:
  - store
extra-deps:
  - github: haskoin/haskoin-core
    commit: 88b68285e815ed658b49ab98be77b6834c6ecb97
  - github: haskoin/haskoin-node
    commit: 315e1dca7f007071e5ee7c6a926b7032a15e00b7
  - github: haskoin/secp256k1-haskell
    commit: 239159122cc6f830957759a1d247ded7ffeba915
  - github: jprupp/nqe
    commit: acbed8c6f39055b33e9c24de3ce634cfc2d8de88
  - ./data
