resolver: lts-17.12
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - git: https://github.com/haskoin/haskoin-core.git
    commit: 73fcd3c401ab38995802b4ccf9e2043eb00b6ff2
  - git: https://github.com/haskoin/haskoin-node.git
    commit: 35ad6937bc0fceaa05385582ffd2b8f17f7d9b49
