resolver: lts-18.10
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - haskoin-core-0.20.5
  - haskoin-node-0.17.14
