resolver: lts-12.20
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
extra-deps:
  - rocksdb-haskell-1.0.1
  - murmur3-1.0.3
  - secp256k1-haskell-0.1.4
  - nqe-0.6.1
  - haskoin-core-0.8.2
  - rocksdb-query-0.2.0
  - haskoin-node-0.9.5
