resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
packages:
  - store
  - data
extra-deps:
  - haskoin-core-0.15.0
  - haskoin-node-0.16.0
  - secp256k1-haskell-0.4.0
  - nqe-0.6.3
  - rocksdb-query-0.4.2
  - rocksdb-haskell-jprupp-2.1.3
