resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - nqe-0.6.3
  - git: https://github.com/haskoin/haskoin-core.git
    commit: 166e4b8565b630c4103557a02a94d201eea6ae16
  - git: https://github.com/haskoin/haskoin-node.git
    commit: 93d9e4eadf79089a0ab32dc27ab3f209c8994ed4
  - secp256k1-haskell-0.4.0
  - rocksdb-query-0.4.2
  - rocksdb-haskell-jprupp-2.1.3
