resolver: lts-18.16
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - haskoin-node-0.17.14
  - git: https://github.com/haskoin/haskoin-core.git
    commit: ffb7b44f989a5a0803ac9777d508d327842f9bf5
