resolver: nightly-2020-11-17
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - haskoin-core-0.17.3
  - haskoin-node-0.17.1
