resolver: lts-16.18
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
    - cacert
packages:
  - store
  - data
extra-deps:
  - nqe-0.6.3
  - haskoin-core-0.17.0
  - haskoin-node-0.17.0
  - secp256k1-haskell-0.5.0
  - rocksdb-query-0.4.2
  - rocksdb-haskell-jprupp-2.1.3
