resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
packages:
  - store
extra-deps:
  - github: haskoin/haskoin-core
    commit: d313ac58b2f22fa7570a5e1234244b7249a48382
  - github: haskoin/haskoin-node
    commit: 05a1e0e5f6e853f94123d849e15b4d447a410e4e
  - github: haskoin/secp256k1-haskell
    commit: 239159122cc6f830957759a1d247ded7ffeba915
  - ./data
