resolver: lts-16.0
nix:
  packages:
    - perl
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
packages:
  - store
extra-deps:
  - haskoin-node-0.13.0
  - haskoin-core-0.13.6
  - secp256k1-haskell-0.2.2
  - ./data
